### ISSUE TITLE
signature是短的

### ISSUE THREAD

**Issue by Brodieee** [AlfredZKY/learn_js#1]
您好,这样生成的signature是短的,加上这个可以生成长的,但是会报错,您能帮忙看一下吗
` window.byted_acrawler.init({
                aid: 24,
                dfp: true
            });`

**Comment by AlfredZKY** [comment]
这个直接是从源码中抽取出来的，网站应该是改版了，需要重新改下。

**Comment by AlfredZKY** [comment]
![image](https://user-images.githubusercontent.com/32631293/79562114-0fd58280-80dd-11ea-8fe3-c395f8fabf3e.png)
